### ISSUE TITLE
Task with name 'compileKotlin' not found in project ':app'.

### ISSUE THREAD

**Issue by droidxrx** [izhangzhihao/unmeta#2]
An exception occurred applying plugin request [id: 'io.github.izhangzhihao.unmeta', version: '1.0.0']
> Failed to apply plugin 'io.github.izhangzhihao.unmeta'.
   > Task with name 'compileKotlin' not found in project ':app'.

**Comment by izhangzhihao** [comment]
make sure you have the gradle kotlin plugin applied.
https://github.com/izhangzhihao/unmeta#by-using-the-kotlin-dsl-in-buildgradlekt

**Comment by rushiiMachine** [comment]
> make sure you have the gradle kotlin plugin applied. [izhangzhihao/unmeta#by-using-the-kotlin-dsl-in-buildgradlekt](https://github.com/izhangzhihao/unmeta#by-using-the-kotlin-dsl-in-buildgradlekt)

AGP replaces `compileKotlin` with `compileReleaseKotlin` and `compileDebugKotlin`, I already have KGP applied

**Comment by izhangzhihao** [comment]
AGP is not supported yet, you can submit a pr to support AGP.

**Comment by axzae** [comment]
I have created a AGP plugin at https://github.com/axzae/unmeta-gradle-plugin

The plugin will only remove `@DebugMetadata` on release build. 
Removing `@Metadata` is causing build failure as it's needed during `hiltJavaCompile` compilation task
