### ISSUE TITLE
Doesn't work for Desktop Apps, like Compose Desktop

### ISSUE THREAD

**Issue by Shabinder** [izhangzhihao/unmeta#4]
## 🐛 Describe the bug

Even after applying the plugin in project with compileKotlinJvm, DebugMetadata annotations are still there.

## ⚠️ Current behavior

Same as said, DebugMetadata still there.

## ✅ Expected behavior

DebugMetadata ,etc annotations should be stripped away.

## 💣 Steps to reproduce

 - build a compose desktop app,
 - add this plugin
 - build output binary, ex: packageReleaseDmg,
 - Analyze the output .jar files in binary, all annotations still there.

## 📷 Screenshots

<img width="383" alt="image" src="https://github.com/user-attachments/assets/23f09bff-d0de-425b-8929-7879e21f4c3d">

**Comment by izhangzhihao** [comment]
make sure you followed the README, and check the gradle dry run plan.
